<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Serie', 'doctrine');

/**
 * BaseSerie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Episode
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getEpisode() Returns the current record's "Episode" collection
 * @method Serie               setId()      Sets the current record's "id" value
 * @method Serie               setName()    Sets the current record's "name" value
 * @method Serie               setEpisode() Sets the current record's "Episode" collection
 * 
 * @package    serialkiller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSerie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('serie');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 126, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 126,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Episode', array(
             'local' => 'id',
             'foreign' => 'show'));
    }
}