<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Episode', 'doctrine');

/**
 * BaseEpisode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $season
 * @property integer $episode
 * @property string $name
 * @property integer $show
 * @property Serie $Serie
 * @property Doctrine_Collection $Link
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method integer             getSeason()  Returns the current record's "season" value
 * @method integer             getEpisode() Returns the current record's "episode" value
 * @method string              getName()    Returns the current record's "name" value
 * @method integer             getShow()    Returns the current record's "show" value
 * @method Serie               getSerie()   Returns the current record's "Serie" value
 * @method Doctrine_Collection getLink()    Returns the current record's "Link" collection
 * @method Episode             setId()      Sets the current record's "id" value
 * @method Episode             setSeason()  Sets the current record's "season" value
 * @method Episode             setEpisode() Sets the current record's "episode" value
 * @method Episode             setName()    Sets the current record's "name" value
 * @method Episode             setShow()    Sets the current record's "show" value
 * @method Episode             setSerie()   Sets the current record's "Serie" value
 * @method Episode             setLink()    Sets the current record's "Link" collection
 * 
 * @package    serialkiller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEpisode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('episode');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('season', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('episode', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 126, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 126,
             ));
        $this->hasColumn('show', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Serie', array(
             'local' => 'show',
             'foreign' => 'id'));

        $this->hasMany('Link', array(
             'local' => 'id',
             'foreign' => 'episode'));
    }
}