<?php

/**
 * Episode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    serialkiller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Episode extends BaseEpisode
{
  
  public static function insertEpisode(Serie $serie, $season, $episodeNum, $title, $date)
  {
    if ($serie instanceof Serie) {
    $episode = EpisodeTable::getInstance()
        ->findOneByName($title);
    
    if ($episode == null) {
      $episode = new Episode();
    }
    $episode->serie = $serie->id;
      $episode->name = $title;
      $episode->season = $season;
      $episode->episode = $episodeNum;
      $episode->date = $date;
      $episode->save();
      return $episode; 
    
    
      
    } else {
      throw Exception;
    }
    
  }
  
  
}
