<?php

/**
 * SerieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SerieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SerieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Serie');
    }
}