<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/05 09:32:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=serialkiller',
  'username' => 'serial_user',
  'password' => 's3r14l',
  'name' => 'doctrine',
)),);
