Episode:
  connection: doctrine
  tableName: episode
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    season:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    episode:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(126)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    serie:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    date:
      type: date
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Serie:
      local: serie
      foreign: id
      type: one
    Link:
      local: id
      foreign: episode
      type: many
Link:
  connection: doctrine
  tableName: link
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    url:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    episode:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Episode:
      local: episode
      foreign: id
      type: one
Serie:
  connection: doctrine
  tableName: serie
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(126)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Episode:
      local: id
      foreign: serie
      type: many
